// <auto-generated />
using MediaCatalog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace MediaCatalog.Migrations
{
    [DbContext(typeof(MediaContext))]
    [Migration("20180527213300_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("MediaCatalog.Models.Media", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duration");

                    b.Property<string>("Format");

                    b.Property<string>("Genre");

                    b.Property<string>("Location");

                    b.Property<string>("MediaType");

                    b.Property<string>("Notes");

                    b.Property<int>("Rating");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.HasKey("ID");

                    b.ToTable("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
